accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.core.urlresolvers import reverse_lazy

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="login.html"), name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r'^profile/$', views.profile_view, name='profile_view'),
]

blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$',views.PostListView.as_view(), name='post_list'),
    url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^post/(?P<pk>\d+)/star/$', views.StarView, name='like_post'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    url(r'', include('blog.urls')),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)

    about = models.CharField(max_length = 225,blank = True)
    # pip install pillow to use this!
    profile_pic = models.ImageField(upload_to="media/profile_pics", blank=True)

    def __str__(self):
        return self.user.username

blog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    blog_pic = models.ImageField(upload_to="blog_pics", blank=True)
    stars = models.ManyToManyField(User, default=63)

    def get_absolute_url(self):
        return reverse("post_detail",kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

    def star_count(self):
        return self.stars.count()




class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse("post_list")

    def __str__(self):
        return self.text

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from accounts.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirmPassword = forms.CharField(widget=forms.PasswordInput(), label="Confirm Password")

    # To hash the password
    def save(self, commit=True):
        User = super().save(commit=False)
        User.set_password(self.cleaned_data["password"])
        if commit:
            User.save()
        return User


    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')





class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('about', 'profile_pic')

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text', 'blog_pic',)

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

        widgets = {
            'author': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
        }

accounts/views.py
from django.shortcuts import render
from accounts.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import login, logout, views
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView

# Create your views here.
class SignUp(CreateView):
    form_class = UserForm
    success_url = reverse_lazy("accounts:login")
    template_name = "signup.html"


def profile_view(request):
    # u = User.objects.get(username=username)
    return render(request, 'accounts/profile_detail.html')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from blog.models import Post, Comment
from django.utils import timezone
from blog.forms import PostForm, CommentForm

from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

# def PostListView(request):
#     if request.method == 'GET':
#         # getting all the objects of hotel.
#         post_list = Blog.objects.all()
#         return render(request, 'blog/blog_list.html', {'post_list' : post_list})

def StarView(request, pk):
    post = get_object_or_404(Post, id = request.POST.get('post_id'))
    post.stars.add(request.user)
    return HttpResponseRedirect(reverse('post_list'))

class PostListView(ListView):
    model = Post
    template_name = 'blog/blog_list.html'

    def get_queryset(self):
        return Post.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')

class PostDetailView(DetailView):
    model = Post

class CreatePostView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/blog_detail.html'
    form_class = PostForm
    model = Post


class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/blog_detail.html'
    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('post_list')

#######################################
## Functions that require a pk match ##
#######################################


@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form': form})


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('post_detail', pk=post_pk)

templates/accounts/profile_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block body_block %}
  <h1 style="text-align: center; color: black;">Profile View</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/e7d8e9b208.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg" style="padding:10px; background-color:#c21d1d">
      <div class="container-fluid">

          <div class="navbar-header">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#example-navbar">
                <i class="fas fa-bars"></i>
              </button>
              <a class="navbar-brand" href="{% url 'post_list' %}"><b style="color:black; font-size: 21px">MySite</b></a>
          </div>

          <div  class="collapse navbar-collapse" id="example-navbar">
            <!-- <ul class="nav navbar-nav">
              For the both logined and not logined users
            </ul> -->

            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                {% if user.is_superuser %}
                  <li><a href="{% url 'admin:index' %}" class="nav-link ml-3"><b style="color:black; font-size: 18px;">Admin</b></a></li>
                  <li><a href="{% url 'post_new' %}" class="nav-link ml-3"><b style="color:black; font-size: 18px;">Create Blog</b></a></li>
                {% endif %}
                <li><a href="{% url 'accounts:profile_view' %}" ><i class="fas fa-user-circle" style="font-size:20px; color:black"></i><b style="color:black; font-size: 18px;">&nbsp;{{ user.username }}</b></a></li>
                <li><a href="{% url 'accounts:logout' %}" class="nav-link ml-3"><b style="color:black; font-size: 18px;">Logout</b></a></li>
              {% else %}
                <li><a href="{% url 'accounts:login' %}" class="nav-link ml-3"><b style="color:black; font-size: 18px;">Login</b></a></li>
                <li><a href="{% url 'accounts:signup' %}" class="nav-link ml-3"><b style="color:black; font-size: 18px;">Sign Up</b></a></li>
              {% endif %}

            </ul>
          </div>

      </div>
    </nav>

    <div class="container">
      {% block body_block %}
        <!-- Anything outside of this will be inherited if we extend! -->
      {% endblock %}
    </div>

  </body>
</html>

templates/blog/post_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block body_block %}
  <div class="container">
    <h1>{{ post.title }}</h1>
    <small style="font-size: 10px"><b>{{ post.created_date }}</b></small>
    <hr style="height:1px;background-color:black">
    <p style="font-size: 17px">{{ post.text }}</p>
  </div>
{% endblock %}

templates/blog/post_form.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block body_block %}
<style>
  .i-am-centered {
    margin: auto;
    max-width: 50%;
    padding: 5%;
    padding-top: 3%;
    border: 2px solid black;
  }
</style>

<div class="i-am-centered container mb-5">

  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <h1 class="mb-4" style="text-align: center; color: black;">Create New Blog   :</h1>
    <div class="form-group" style="font-size: 15px; color: black;">
      <label>Blog Title:&nbsp; &nbsp; &nbsp;</label>
      {{ form.title }}
    </div>
    <div class="form-group" style="font-size: 15px; color: black;">
      <label>Blog Content:&nbsp; &nbsp; &nbsp; </label>
      {{ form.text }}
    </div>
    <div class="form-group" style="font-size: 15px; color: black;">
      <label>Blog Picture:&nbsp; &nbsp; &nbsp; </label>
      {{ form.blog_pic }}
    </div>

    <div style="text-align: center;">
      <button type="submit" class="btn btn-info btn-lg" style="text-align: center;"><b style="font-size: 15px; padding: 5px;" >Create</b></button>
    </div>

  </form>
</div>
{% endblock %}

templates/blog/post_list.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block body_block %}
  <div class="centerstage">
    {% for post in post_list %}
        <div class="post">
          <div class="col-md-6 col-md-offset-3">
            <div class="thumbnail">
              <div class="caption">
                <h3><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a> <div style="text-align: right;">
                <form action="{% url 'like_post' post.pk %}" method = "POST">
                  {% csrf_token %}
                  <button type="submit" value="{{ post.id }}"><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span></button>
                </form>
                </div> </h3>
                <small><b>{{ post.created_date|date:"M d, Y"}}  <div style="text-align: right;"><span>{{ post.stars }}</span></div> </b></small>
              </div>
              <img src="{{ post.blog_pic.url }}" class="img-responsive"/>
            </div>
          </div>

        </div>
    {% endfor %}
</div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block body_block %}

<style>
  .i-am-centered {
    margin: auto;
    max-width: 50%;
    padding: 5%;
    padding-top: 3%;
    border: 2px solid black;
  }
</style>

<div class="container i-am-centered container">
  <form method="POST">
      {% csrf_token %}
      <h1 class="mb-4" style="text-align: center; color: black;">Login Form   :</h1>
      <div class="form-group" style="font-size: 15px; color: black;">
        <label>UserName:&nbsp; &nbsp; &nbsp; </label>
        {{ form.username }}
      </div>
      <div class="form-group" style="font-size: 15px; color: black;">
        <label>Password:&nbsp; &nbsp; &nbsp; </label>
        {{ form.password }}
      </div>
      <div style="text-align: center;">
        <button type="submit" class="btn btn-info btn-lg" style="text-align: center;"><b style="font-size: 15px; padding: 5px;">Login</b></button>
      </div>
  </form>
</div>
{% endblock %}

templates/signup.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
	<style>
		.i-am-centered {
			margin: auto;
			max-width: 50%;
			padding: 5%;
      padding-top: 3%;
      border: 2px solid black;
		}
	</style>

	<div class="i-am-centered container">
    {% if registered %}
      <h1 style="text-align: center;">Thank you for signing up!!</h1>
      <h2 style="text-align: center;" class="mt-2">Continue browsing and share your expirence and any new topic to discuss in the feedback section. We will happy to get your response :) </h2>
    {% else %}
		<form method="POST">
			{% csrf_token %}
      <h1 class="mb-4" style="text-align: center; color: black;">Sign Up Form   :</h1>
			<div class="form-group" style="font-size: 15px; color: black;">
				<label>First Name:&nbsp; &nbsp; &nbsp;</label>
				{{ form.first_name }}
			</div>
			<div class="form-group" style="font-size: 15px; color: black;">
				<label>Last Name:&nbsp; &nbsp; &nbsp; </label>
				{{ form.last_name }}
			</div>
			<div class="form-group" style="font-size: 15px; color: black;">
				<label>UserName:&nbsp; &nbsp; &nbsp; </label>
				{{ form.username }}
			</div>
      <div class="form-group" style="font-size: 15px; color: black;">
        <label>Email Address:&nbsp; &nbsp; &nbsp; </label>
        {{ form.email }}
      </div>
			<div class="form-group" style="font-size: 15px; color: black;">
				<label>Password:&nbsp; &nbsp; &nbsp; </label>
				{{ form.password }}
			</div>
      <div class="form-group" style="font-size: 15px; color: black;">
        <label>Confirm Password: &nbsp; &nbsp; &nbsp;</label>
        {{ form.confirmPassword }}
      </div>
      <div style="text-align: center;">
        <button type="submit" class="btn btn-info btn-lg" style="text-align: center;"><b style="font-size: 15px; padding: 5px;" >Sign Up</b></button>
      </div>
    {% endif %}

		</form>
	</div>

{% endblock %}